### PR TITLE
Added scenario driven Beacon query

### PR DESCRIPTION
**Pull request by victorskl**
* Improved linking pointers better visibility to sources

### CODE REVIEW

**Review by reisingerf — APPROVED** [review]
Awesome!

**Comment by reisingerf** [comment]
The filtering query does still not work fully or did you fix it?

**Review by victorskl — COMMENTED** [review]
> The filtering query does still not work fully or did you fix it?

Yup. We need to fix it. It might be something related to "relation" table and missing of meta "Run" info issue that discussed with @anuradhawick Let add and mock that Run info for CINECA.

Also. We should re-point to Hg38 liftover VCF by Conrad too! cc @delocalizer

:)

**Comment by victorskl** [comment]
Merging this for now

**Pull request merged**
